version: "3"
services:
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        ports:
            - "3200:3000"

    loki:
        image: grafana/loki
        ports:
            - "3100:3100"
        # command: -config.file=/etc/loki/local-config.yaml
        # volumes:
        #   - ./loki:/etc/loki

    # rabbitmq:
    #   image: rabbitmq:management
    #   ports:
    #     - "5672:5672"
    #     - "15672:15672"
    #   environment:
    #     - RABBITMQ_DEFAULT_USER=admin
    #     - RABBITMQ_DEFAULT_PASS=admin

    # redis:
    #   image: redis
    #   ports:
    #     - "6379:6379"
# ---------------------------

# 1. Create Configuration Files

# Prometheus Configuration (prometheus/prometheus.yml)
# yaml
# Copy code
# global:
#   scrape_interval:     15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

# 2. Loki Configuration (loki/local-config.yaml)

# auth_enabled: false
# server:
#   http_listen_port: 3100
# ingester:
#   lifecycler:
#     address: 127.0.0.1
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#   chunk_idle_period: 15m
#   chunk_retain_period: 15m
#   max_transfer_retries: 0
# schema_config:
#   configs:
#     - from: 2020-01-01
#       store: boltdb
#       object_store: filesystem
#       schema: v11
#       index:
#         prefix: index_
#         period: 168h
# storage_config:
#   boltdb:
#     directory: /tmp/loki/boltdb
#   filesystem:
#     directory: /tmp/loki/chunks
# limits_config:
#   reject_old_samples: true
#   reject_old_samples_max_age: 168h
# chunk_store_config:
#   max_look_back_period: 0s
# table_manager:
#   retention_deletes_enabled: false
#   retention_period: 0s

# 3. Please create local directory:

# mkdir prometheus loki

# 3. docker-compose up -d

