version: "3"

services:
    # mysql:
    #     image: mysql:latest
    #     container_name: mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 1234
    #         MYSQL_DATABASE: user-posts
    #         MYSQL_USERNAME: root
    #         MYSQL_PASSWORD: 1234

    rabbitmq:
        image: rabbitmq:latest
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - my-network
    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        ports:
            - "6831:6831/udp" # jaeger-agent thrift compact port
            - "6832:6832/udp" # jaeger-agent thrift binary port
            - "5778:5778" # jaeger-agent admin HTTP port
            - "16686:16686" # jaeger-ui port
            - "14268:14268" # jaeger-collector port
            - "14250:14250" # jaeger-collector thrift HTTP port
            - "9411:9411" # jaeger-collector thrift compact port

    user_service:
        image: hackathon_users_image
        container_name: users_service
        build:
            context: ../user-service
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3001:3001"
        environment:
            - RABBITMQ_MQ=amqp://rabbitmq
        depends_on:
            # - mysql
            - rabbitmq
            # - redis

    tasks_service:
        image: hackathon_tasks_image
        container_name: tasks_service
        build:
            context: ../task-service
            dockerfile: Dockerfile
        restart: always
        ports:
            - "4000:4000"
        environment:
            - MYSQL_USER=root
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - RABBITMQ_MQ=amqp://rabbitmq
            - REDIS_URL=redis://54.145.6.11:6379
            # - MYSQL_URL=mysql
            - MONGODB=mongodb+srv://dnsdhrubo:jVGflASJlCR5Xy2B@cluster0.xhxuxg5.mongodb.net/hackathon
        depends_on:
            # - mysql
            - rabbitmq
            - redis      

networks:
    my-network:
        driver: bridge
